# Generated by Django 3.2.15 on 2022-09-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosone', models.JSONField(default={'chromosone': []})),
            ],
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_value', models.FloatField()),
                ('chromosone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.solution')),
            ],
        ),
    ]
