# Generated by Django 3.2.15 on 2022-09-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitness',
            old_name='chromosone',
            new_name='solution',
        ),
    ]
